name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
     strategy:
      matrix:
       api-level: [30]
       target: [default]
     
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Espresso Tests 
    uses: ReactiveCircus/android-emulator-runner@v2.21.0
  with:
  api-level: 30
  target: default
  arch: x86
  profile: Nexus 6
  run: ./gradlew build
  script: ./gradlew LoginTestDemo
